<?php


class TestDonut extends \App\Decorator\DonutDecorator
{
    public function getDescription(): string
    {
        return (string) "Test " . $this->donut->getDescription();
    }

    public function getCost(): float
    {
        return (string) ((float) 1 + $this->donut->getCost());
    }
}

class TestConcreteDonut implements \App\Contracts\Donut
{
    public function getDescription(): string
    {
        return (string) "Donut";
    }

    public function getCost(): float
    {
        return (float) 1;
    }
}

class DonutDecoratorTest extends \PHPUnit\Framework\TestCase
{
    protected $sut;

    protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->sut = new TestConcreteDonut();
    }

    public function testGetCost() : void
    {
        $this->assertEquals((float) 1, $this->sut->getCost());
    }

    public function testGetDescription () : void
    {
        $this->assertEquals((string) "Donut", $this->sut->getDescription());
    }

    public function testInjectDependency () : void
    {
        $testDonut = new TestDonut(new TestConcreteDonut());
        $this->assertEquals((float) 2, $testDonut->getCost());
        $this->assertEquals((string) "Test Donut", $testDonut->getDescription());
    }
}